name: Build Frontend

on:
  push:
    branches:
      - main  # Замени на master, если основная ветка называется так

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверяем код из репозитория
        uses: actions/checkout@v4

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Устанавливаем зависимости
        run: npm ci # или npm install, если нет package-lock.json

      - name: Собираем проект
        run: npm run build

      - name: Сохраняем готовую папку public
        uses: actions/upload-artifact@v4
        with:
          name: public-dist
          path: public/

